server:
  port: 8080 # Puerto estándar del Gateway [2, 3]

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Ruta para el primer servicio
        - id: ms-catalogo
          uri: lb://ms-catalogo # Usa lb:// para buscar en Eureka [1, 4]
          predicates:
            - Path=/api/catalogo/**

        # Repite este bloque para ms-usuarios, ms-pedidos, etc.