spring:
  application:
    name: api-gateway  # <--- ESTO QUITA EL "UNKNOWN"
  
  cloud:
    gateway:
      server:
        webflux: # <--- ESTO QUITA LOS WARNINGS DE MIGRACIÓN
          routes:
            - id: ms-catalogo
              uri: lb://MS-CATALOGO
              predicates:
                - Path=/api/catalogo/**
            - id: ms-inventario
              uri: lb://MS-INVENTARIO
              predicates:
                - Path=/api/inventario/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/